{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "leansignal-agent.serviceAccountName" . }}
  labels:
    {{- include "leansignal-agent.labels" . | nindent 4 }}
{{- end }}
